language: node_js
node_js: "node"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
script:
    - make test && ( [ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || ( make browserstack && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls ) )
env:
    global:
        - CXX=g++-4.8
        - secure: bUyIN5cHVHRnihJw4z84nKhpp8LRy1WwqdI1n134HHZ1UnS52t0XfNRiO0iwmJmyT5TeHXqNEKN6IpvWUAdM8his2bvoAurNdoH3BELFXWz66esw/dNpl9pUy/mEgTsLnzCIIUcvIdVz6iSeH4aiBzImbuKS9JT2zzLZaSCpoKeNitRTHpuYd1wSaNmaNkdB6u5oy+YV1snzJuFQ4JetezmfZy4pEYrPYdxwh7YTigqQhRchoBvhHVRtyIxRjp9GNl5cITtYOejfMa2zuj6ISoDg04QslS3XQVX6MEUmTzlQBwZYBWFIbfOzkgdxk3wVXwi1QsgQEKN4781VJ3PrYpgxzCSRRpHfftCoWnhlunS953KGjqcf85MhcF/jZpKpM6LT5j2b52c2VJvSR2H2G/5NTGCBEdM+NUlQblHzqfGl/Iz0fYAhHuEDq3KiOPt7WCCfcu4YeLcih2MGsllnRJx4lrTisVtMTk1EZMaqnH0ChHbPX/Yo34VWoD0ByfGBhEFtgR5QbOYOTXldjq2BZKKEi1uA/bKA0Ey4Q9Q0xCfPc1VfD/8cAQooHTA5ta8C3w1/sxr7jNRX72c9C/JBL532BI0Gdng8PAl9Qvgj6xSmmPcXK5KWfmtAo/BIVwUtswk6WsmnHI7kfvAQv5CnpH9Azup9fO0jlCLCcjbhIH8=
        - secure: smI7rQrcoYErPOTruGINXzo8BHzlcevTY9GXdq7cbvfSkXmGYVqAQ/Vy2KjAe36iIlifsOKuvMlFQNQgghGHaZkO2Ol4hSfVu8UMKmQ8mEi+E5LSSwIY4NEPDrwVADXuzZjow329riutvuauEifJn+WNLDey/bFbBdKKIW4hYK9kiXvMwOlDmRwDMgZzw/IJgPCrmT2XKqDGofSnP75NMRj71HrctsxH2INHKFbGRvwIcCEUH6T3ifhBXdQaRPkcxfgvrvsUjxW8PiUlQI+TswgbTVsT/1UtejHcr1y5DYOj8e6BEbSOC+/KPrsj/YuCSgRiV4Qy+Ab2pM32kCKYpJJMPRUhzNnd9uauV2NXqLSRyPmCn41VFZnQlgSNc6DhWxDOuEg+cokcS5p0i1PpMxiaRZVtEYjgKUi0ETKotr+c+WJWSFQN3SWySGjQ0NiUvTWhrChEBbWQNVgRhF9jMNQQoEYWSlppo4ek5S7VyLPRRl0cz88zPdcKKKpmuktZxY7CQ/Bk3zcEz6EhaDaWE1YBuLeZAKtdlgEZ9zFhMFU6YZso5x1FhpX1xbwWuulG/HycZD44KhB2kDDCgTJ8BGDxkneOsTLMUAsXZbs8iYMLwRfwuSlmrQNKrlrfcSIpEVqDd2y8j3PSfXk+pjaLtJ2wfvT542FpHqxcvVwF8Ig=
before_deploy:
    - make cq-prolyfill.min.js
    - make cq-prolyfill.min.js.gz
deploy:
    -
        provider: releases
        api_key:
            secure: j0eUc5q6S3/P/iL36xhw6MYFrRP9986dv9WGwF1o9HlmmtkTR0ts7zhvY8dQK5Pp2LAaYCT1HokNCfvu9FDoNTIpn5o9mFLXbe7pBbFX2wg2QKc5iN5x19TOiMPLfQhatgaJ1x7Cbp/kANbR8ZtCjfrEQJZDI0IR68DdD6FH1Uq87a3F3AgkzqD5YCZu4G17ZpLophZIPFKk2SUcE6Kmdk9JW0lo+D/ubP4OwXL131CrS7M1KU1yChTHmquplwQ0lTe7n6+mOU/Xhi8NihXj0h2TzKrw9DRBEHi5e4RZbwJ2/jv86LcjTRO23jkX0i8XKQgqzHCbFfwfK6ExGh5ihqJpVTF8o1wdQZpXX6Tf7ALnqkK5o3V2j474B26qvHNOClB4lThfDaWJtp+/8y5vjE5okSHO95ZlCPt7FzugsgigfyC+M/b514BbfXL2MhZUpKsEjdLuPkAR2YJVs1Rbaw1GOuLlSI+jKWiU+uUDH+e1uuTc68gfzM/UJ+8tcB6Z38c3f4a7yKaF6SjJDPJgHPkpoCV6DXFUPgkn+UypWGkN/Vs9k/3+y1qaPIF3AN5v+2Rcn0u/FW6wa0SRqXF0g53mGNZRcIAKhz1/XQpYWyE6p9Y5eRSIVD73iLkHCr7uR5Oxs9blSqAsCn1e4XLmienUhiXQcy804raP15ZWQxk=
        file:
            - cq-prolyfill.js
            - cq-prolyfill.min.js
            - cq-prolyfill.min.js.gz
        skip_cleanup: true
        on:
            tags: true
    -
        provider: npm
        email: martin@auswoeger.com
        api_key:
            secure: ljq7zGzA0NJx5ykcDtLf1g+KaCeMmTzFvcWbKRdYw51JzSIxKdJv/C45ovVnUUPBrnI1oNLW5qk5IO3wh7obW+2OsWafHU/okG/ZWmword48IomnvZmIAjMF6GwJ5ZT2EU44wCSC7zZrMMFszPqyoKi45DVKTxthw2IztU0klRvzXlP4AZ1vGR8zYCGOG3rR6iLe4HY4ZNNpRFBj+ONC7VBZERQ5DsZZDcMXcZpnDTEvbn6HCycpR7N5NJgcCfTLm1KWW8yQZNVAaEtuaCpw0Z1I5E3TSZFfl2xV3ES5Kg6qSi18M/EkZ9aXPoU3JrAMiTGTH0R+6PSe7E0GdB+PBLZ8smk6/nAbHdd+BlsvEj/B70l8vWlwo+0giaZSQ0wb8g9KbQClP9txaCCjMF2Z9vFPlXtokIjwhQfGQ46xg7DjEkURoVVtlPxhPdiZ4D1MnkasMhuJGLfidVGkgcMLQxc2CG4xdQm9nIH3izWTYOvPVK0SPSt+pRSLIHnDeswAg2EwMEhneYdyOo0Yjs7I82fppFdJmZ9jbyeskLdn9u5dQh15CN7TK4e6JJNBPADs8bJiWSuKOHXRnfRqXz0mEFbHQ+YZcojINyVDXmhqxI/xvRu9vCeAp9jvm+l8CsPvs/735v+HswFZkiqo0acLjOVqNsH9/e3wXETLcAWgZYE=
        skip_cleanup: true
        on:
            tags: true
